version: '3'

services:

  prometheus:
    image: jahrik/arm-prometheus:arm32v7
    ports:
      - 9090:9090
    volumes:
      - /mnt/g1/prometheus:/prometheus
    dns:
      - bebop
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # - node.role == manager
          - node.labels.arch == aarch64
