version: '3.5'

services:

  prometheus:
    image: jahrik/arm-prometheus:aarch64
    ports:
      - 9090:9090
    volumes:
      - /mnt/g1/prometheus:/prometheus
    networks:
      - monitor
      - elk
      - traefik
    dns:
      - bebop
    deploy:
      placement:
        constraints:
          - node.labels.arch == aarch64

networks:
  elk:
    driver: overlay
    external: true
  traefik:
    driver: overlay
    external: true
  monitor:
    name: monitor
    driver: overlay
